spring:
  application.name: "demo"
  profiles.active: "dev"

--- #prod
spring:
  config.activate.on-profile: "prod"
  sql.init.mode: never
  datasource:
    url: "jdbc:mysql://localhost/accounts_db"
    username: "account_user"
    password: "acc123"
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      generate-ddl: false
      ddl-auto: update
    defer-datasource-initialization: false
server:
  port: 9943
  servlet.context-path: "/api/v1"
logging:
  level.root: ERROR
--- #dev

spring:
  config.activate.on-profile: "dev"

  sql.init.mode: "always"
  datasource:
    url: "jdbc:h2:mem:demodb"
    driverClassName: org.h2.Driver
    username: grupo3
    password: grupo3
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui
server:
  port: 9900
#logging:
 # level.root: DEBUG
 # file.path: "/var/logs/accounts.log"
---

